# The workflow will build a Forge Mod with Gradle
#
# creator: boomboompower
# version: 1.0

name: Java CI with Forge

# Trigger the integration for pull requests and pushes
# to every branch on the repository
on: [push]

jobs:
  windows:
    name: Windows Mod CI

    # Use latest windows version
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Sets up the forge workspace (using CI)
      - name: Launch Forge Workspace
        run: ./gradlew setupCIWorkspace clean

        # Uses ForgeGradle to build the jar
      - name: Build with Gradle
        run: ./gradlew build

  linux:
    name: Linux Mod CI

    # Use latest linux distro
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Required so gradlew can build the JAR file
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Sets up the forge workspace (using CI)
      - name: Launch Forge Workspace
        run: ./gradlew setupCIWorkspace clean

        # Deletes any unnecessary files which shouldn't
        # exist in the first place.
      - name: Clean output directories
        run: |
          rm -f -R out
          rm -f -R build

        # Uses ForgeGradle to build the jar
      - name: Build with Gradle
        run: ./gradlew build

      # Upload the main mod to the artifacts tab
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          body: Automagically generated for ${{ github.action }} with id ${{ github.run_number }}
          draft: false
          prerelease: true
      - name: Upload Mod
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: './build/libs/SkinChangerMod.jar'
          asset_name: SkinChangerMod.jar
          asset_content_type: application/zip
      - name: Upload Mod Sources
        id: upload-sources-asset 
        uses: actions/upload-release-asset@v1
        
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: './build/libs/SkinChangerMod-sources.jar'
          asset_name: SkinChangerMod-sources.jar
          asset_content_type: application/zip
        
  macOS:
    name: macOS Mod CI

    # Use latest macOS version
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Required so gradlew can build the JAR file
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Sets up the forge workspace (using CI)
      - name: Launch Forge Workspace
        run: ./gradlew setupCIWorkspace clean

        # Uses ForgeGradle to build the jar
      - name: Build with Gradle
        run: ./gradlew build
