# This workflow will build a Java project with Gradle and Forge
# The workflow will generate a mod file and publish it to Github

name: Java CI with Forge

on:
  push:
    branches: [ master, Legacy ]
  pull_request:
    branches: [ master, Legacy ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Launch Forge Workspace
      run: ./gradlew setupCIWorkspace clean

    - name: Build with Gradle
      run: ./gradlew build jar --stacktrace

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
