# This workflow will build a Java project with Gradle and Forge
# The workflow will generate a mod file and publish it to Github

name: Java CI with Forge

on:
  push:
    branches: [ master, Legacy ]
  pull_request:
    branches: [ master, Legacy ]

jobs:
  happy:
    name:  Introduction
    
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Intro
        run: |
          lp "# # # # # # # # # # # # # # # # # # # # # # #"
          lp "                SkinChanger                  "
          lp "        https://do-you-like.me/mods          "
          lp "                                             "
          lp "             by boomboompower                "
          lp "# # # # # # # # # # # # # # # # # # # # # # #"
      - name: Build
        run: |
          lp ":setupBuild"
          lp ":cleanBuild"
          lp ":complete"
          lp " "
          lp "Have a nice day!"
          
  build:
    name: CI Build Mod

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Launch Forge Workspace
      run: ./gradlew setupCIWorkspace clean

      # These files shouldn't exist but we'll try delete them anyway
    - name: Clean output directories
      run: |
        rm -f -R out
        rm -f -R build

      # Uses ForgeGradle to destribute the jar file
    - name: Build with Gradle
      run: ./gradlew --continue build jar --stacktrace

      # Attempts to send the built jar to github
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}

